$data modify storage rv:data ram[$(page)][$(i0)] set value 0
$data modify storage rv:data ram[$(page)][$(i1)] set value 0
$data modify storage rv:data ram[$(page)][$(i2)] set value 0
$data modify storage rv:data ram[$(page)][$(i3)] set value 0
$data modify storage rv:data ram[$(page)][$(i4)] set value 0
$data modify storage rv:data ram[$(page)][$(i5)] set value 0
$data modify storage rv:data ram[$(page)][$(i6)] set value 0
$data modify storage rv:data ram[$(page)][$(i7)] set value 0
$data modify storage rv:data ram[$(page)][$(i8)] set value 0
$data modify storage rv:data ram[$(page)][$(i9)] set value 0
$data modify storage rv:data ram[$(page)][$(i10)] set value 0
$data modify storage rv:data ram[$(page)][$(i11)] set value 0
$data modify storage rv:data ram[$(page)][$(i12)] set value 0
$data modify storage rv:data ram[$(page)][$(i13)] set value 0
$data modify storage rv:data ram[$(page)][$(i14)] set value 0
$data modify storage rv:data ram[$(page)][$(i15)] set value 0
$data modify storage rv:data ram[$(page)][$(i16)] set value 0
$data modify storage rv:data ram[$(page)][$(i17)] set value 0
$data modify storage rv:data ram[$(page)][$(i18)] set value 0
$data modify storage rv:data ram[$(page)][$(i19)] set value 0
$data modify storage rv:data ram[$(page)][$(i20)] set value 0
$data modify storage rv:data ram[$(page)][$(i21)] set value 0
$data modify storage rv:data ram[$(page)][$(i22)] set value 0
$data modify storage rv:data ram[$(page)][$(i23)] set value 0
$data modify storage rv:data ram[$(page)][$(i24)] set value 0
$data modify storage rv:data ram[$(page)][$(i25)] set value 0
$data modify storage rv:data ram[$(page)][$(i26)] set value 0
$data modify storage rv:data ram[$(page)][$(i27)] set value 0
$data modify storage rv:data ram[$(page)][$(i28)] set value 0
$data modify storage rv:data ram[$(page)][$(i29)] set value 0
$data modify storage rv:data ram[$(page)][$(i30)] set value 0
$data modify storage rv:data ram[$(page)][$(i31)] set value 0
$data modify storage rv:data ram[$(page)][$(i32)] set value 0
$data modify storage rv:data ram[$(page)][$(i33)] set value 0
$data modify storage rv:data ram[$(page)][$(i34)] set value 0
$data modify storage rv:data ram[$(page)][$(i35)] set value 0
$data modify storage rv:data ram[$(page)][$(i36)] set value 0
$data modify storage rv:data ram[$(page)][$(i37)] set value 0
$data modify storage rv:data ram[$(page)][$(i38)] set value 0
$data modify storage rv:data ram[$(page)][$(i39)] set value 0
$data modify storage rv:data ram[$(page)][$(i40)] set value 0
$data modify storage rv:data ram[$(page)][$(i41)] set value 0
$data modify storage rv:data ram[$(page)][$(i42)] set value 0
$data modify storage rv:data ram[$(page)][$(i43)] set value 0
$data modify storage rv:data ram[$(page)][$(i44)] set value 0
$data modify storage rv:data ram[$(page)][$(i45)] set value 0
$data modify storage rv:data ram[$(page)][$(i46)] set value 0
$data modify storage rv:data ram[$(page)][$(i47)] set value 0
$data modify storage rv:data ram[$(page)][$(i48)] set value 0
$data modify storage rv:data ram[$(page)][$(i49)] set value 0
$data modify storage rv:data ram[$(page)][$(i50)] set value 0
$data modify storage rv:data ram[$(page)][$(i51)] set value 0
$data modify storage rv:data ram[$(page)][$(i52)] set value 0
$data modify storage rv:data ram[$(page)][$(i53)] set value 0
$data modify storage rv:data ram[$(page)][$(i54)] set value 0
$data modify storage rv:data ram[$(page)][$(i55)] set value 0
$data modify storage rv:data ram[$(page)][$(i56)] set value 0
$data modify storage rv:data ram[$(page)][$(i57)] set value 0
$data modify storage rv:data ram[$(page)][$(i58)] set value 0
$data modify storage rv:data ram[$(page)][$(i59)] set value 0
$data modify storage rv:data ram[$(page)][$(i60)] set value 0
$data modify storage rv:data ram[$(page)][$(i61)] set value 0
$data modify storage rv:data ram[$(page)][$(i62)] set value 0
$data modify storage rv:data ram[$(page)][$(i63)] set value 0
$data modify storage rv:data ram[$(page)][$(i64)] set value 0
$data modify storage rv:data ram[$(page)][$(i65)] set value 0
$data modify storage rv:data ram[$(page)][$(i66)] set value 0
$data modify storage rv:data ram[$(page)][$(i67)] set value 0
$data modify storage rv:data ram[$(page)][$(i68)] set value 0
$data modify storage rv:data ram[$(page)][$(i69)] set value 0
$data modify storage rv:data ram[$(page)][$(i70)] set value 0
$data modify storage rv:data ram[$(page)][$(i71)] set value 0
$data modify storage rv:data ram[$(page)][$(i72)] set value 0
$data modify storage rv:data ram[$(page)][$(i73)] set value 0
$data modify storage rv:data ram[$(page)][$(i74)] set value 0
$data modify storage rv:data ram[$(page)][$(i75)] set value 0
$data modify storage rv:data ram[$(page)][$(i76)] set value 0
$data modify storage rv:data ram[$(page)][$(i77)] set value 0
$data modify storage rv:data ram[$(page)][$(i78)] set value 0
$data modify storage rv:data ram[$(page)][$(i79)] set value 0
$data modify storage rv:data ram[$(page)][$(i80)] set value 0
$data modify storage rv:data ram[$(page)][$(i81)] set value 0
$data modify storage rv:data ram[$(page)][$(i82)] set value 0
$data modify storage rv:data ram[$(page)][$(i83)] set value 0
$data modify storage rv:data ram[$(page)][$(i84)] set value 0
$data modify storage rv:data ram[$(page)][$(i85)] set value 0
$data modify storage rv:data ram[$(page)][$(i86)] set value 0
$data modify storage rv:data ram[$(page)][$(i87)] set value 0
$data modify storage rv:data ram[$(page)][$(i88)] set value 0
$data modify storage rv:data ram[$(page)][$(i89)] set value 0
$data modify storage rv:data ram[$(page)][$(i90)] set value 0
$data modify storage rv:data ram[$(page)][$(i91)] set value 0
$data modify storage rv:data ram[$(page)][$(i92)] set value 0
$data modify storage rv:data ram[$(page)][$(i93)] set value 0
$data modify storage rv:data ram[$(page)][$(i94)] set value 0
$data modify storage rv:data ram[$(page)][$(i95)] set value 0
$data modify storage rv:data ram[$(page)][$(i96)] set value 0
$data modify storage rv:data ram[$(page)][$(i97)] set value 0
$data modify storage rv:data ram[$(page)][$(i98)] set value 0
$data modify storage rv:data ram[$(page)][$(i99)] set value 0
$data modify storage rv:data ram[$(page)][$(i100)] set value 0
$data modify storage rv:data ram[$(page)][$(i101)] set value 0
$data modify storage rv:data ram[$(page)][$(i102)] set value 0
$data modify storage rv:data ram[$(page)][$(i103)] set value 0
$data modify storage rv:data ram[$(page)][$(i104)] set value 0
$data modify storage rv:data ram[$(page)][$(i105)] set value 0
$data modify storage rv:data ram[$(page)][$(i106)] set value 0
$data modify storage rv:data ram[$(page)][$(i107)] set value 0
$data modify storage rv:data ram[$(page)][$(i108)] set value 0
$data modify storage rv:data ram[$(page)][$(i109)] set value 0
$data modify storage rv:data ram[$(page)][$(i110)] set value 0
$data modify storage rv:data ram[$(page)][$(i111)] set value 0
$data modify storage rv:data ram[$(page)][$(i112)] set value 0
$data modify storage rv:data ram[$(page)][$(i113)] set value 0
$data modify storage rv:data ram[$(page)][$(i114)] set value 0
$data modify storage rv:data ram[$(page)][$(i115)] set value 0
$data modify storage rv:data ram[$(page)][$(i116)] set value 0
$data modify storage rv:data ram[$(page)][$(i117)] set value 0
$data modify storage rv:data ram[$(page)][$(i118)] set value 0
$data modify storage rv:data ram[$(page)][$(i119)] set value 0
$data modify storage rv:data ram[$(page)][$(i120)] set value 0
$data modify storage rv:data ram[$(page)][$(i121)] set value 0
$data modify storage rv:data ram[$(page)][$(i122)] set value 0
$data modify storage rv:data ram[$(page)][$(i123)] set value 0
$data modify storage rv:data ram[$(page)][$(i124)] set value 0
$data modify storage rv:data ram[$(page)][$(i125)] set value 0
$data modify storage rv:data ram[$(page)][$(i126)] set value 0
$data modify storage rv:data ram[$(page)][$(i127)] set value 0
